### ISSUE TITLE
Add discussion of performance improvement steps

### ISSUE THREAD

**Issue by maherou** [Collegeville/Lindquist-Neil-Work#1]
The current writeup has some very good content!  

The next section to write is the experience of how to get performance improvement.  Address specific strategies that could be more broadly useful for other Julia programmers.

Also, there should be a section on the computing environment used, with enough information for someone else to execute the same experiments.

**Comment by neil-lindquist** [comment]
I'm having trouble seeing the usefulness of a section on performance improvement, because most of the optimizations I used seem pretty standard, either specifically in Julia or generally in programming.  The one optimization that seems notable is using pointers to access arrays inside the matrix-vector product loop to prevent the creation and deletion of many array view objects.


For the section on the computing environment, I have some notes at the end of the Timing Results section, including Julia, Trilinos, OS and GCC versions, the number and models of the processors and some of the flags used.  A description of the problem and some notes on how it was timed are also present.  Is there more that I should add, or just make the part more obvious?


Here is the list of other optimizations I can think of.  Many appear on https://docs.julialang.org/en/stable/manual/performance-tips/ 
* Profile the code to find the sections that need to be optimized thoroughly
* Making sure the type inferencer knows the concrete type of every variable
* Forcing inlining for method calls in tight loops
* Accessing arrays in memory order
* Creating specialized functions that compute exactly what is needed for use in critical sections, instead of using general use functions
* Skipping index bound checks when the values are guaranteed to be in bounds.
* Using an object pool for frequently created objects (specifically `RowInfo`)

**Comment by neil-lindquist** [comment]
Here is a pdf version of the latest version of the writeup, build from commit 66351f3.
[writeup.pdf](https://github.com/Collegeville/Lindquist-Neil-Work/files/2028591/writeup.pdf)
